---
require:
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - "Gemfile"
  - "spec/**/*"

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Allow to use let!
RSpec/LetSetup:
  Enabled: no

RSpec/MultipleExpectations:
  Enabled: no

Bundler/OrderedGems:
  Enabled: no

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-params-comma'
  Enabled: yes
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Description: 'Checks for trailing comma in array literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  Enabled: yes
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in hash literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  Enabled: yes
  EnforcedStyleForMultiline: consistent_comma

RSpec/FilePath:
  Enabled: no
